
export const columnDefs = [
    { field: "UPC", filter: "agTextColumnFilter",pinned: 'left' },
    { field: "Product Desc", filter: "agTextColumnFilter",pinned: 'left' },
    { field: "Vendor Cost Zone Desc", filter: "agTextColumnFilter" },
    { field: "Vendor Id", filter: "agTextColumnFilter" },
    { field: "# of Stores", filter: "agNumberColumnFilter" },
    { field: "Department", filter: "agTextColumnFilter" },
    { field: "Category", filter: "agTextColumnFilter" },
    { field: "Sub Category", filter: "agTextColumnFilter" },
    { field: "Zone Name", filter: "agTextColumnFilter" },
    { field: "Zone", filter: "agTextColumnFilter" },
    { field: "Price Fam id", filter: "agTextColumnFilter" },
    { field: "# of products", filter: "agNumberColumnFilter" },
    { field: "Export Rev", filter: "agNumberColumnFilter" },
    { field: "Rec Profit Elast Chg", filter: "agNumberColumnFilter" },
    { field: "Markdown Amount", filter: "agNumberColumnFilter" },
    { field: "End Date", filter: "agDateColumnFilter" },
    { field: "Capture Rate", filter: "agNumberColumnFilter" },
    { field: "Exit Date", filter: "agDateColumnFilter" },
    { field: "Markdown Budget", filter: "agNumberColumnFilter" },
    { field: "Markdown Variance", filter: "agNumberColumnFilter" },
    { field: "Item Add Date", filter: "agDateColumnFilter" },
    { field: "Competitor Impactful1", filter: "agTextColumnFilter" },
    { field: "Competitor Price Impactful1", filter: "agNumberColumnFilter" },
    { field: "Competitor Impactful2", filter: "agTextColumnFilter" },
    { field: "Competitor Price Impactful2", filter: "agNumberColumnFilter" },
    { field: "Competitor Priority1", filter: "agTextColumnFilter" },
    { field: "Competitor Price Priority1", filter: "agNumberColumnFilter" },
    { field: "Competitor Priority2", filter: "agTextColumnFilter" },
    { field: "Competitor Price Priority2", filter: "agNumberColumnFilter" },
    { field: "Competitor Priority3", filter: "agTextColumnFilter" },
    { field: "Competitor Price Priority3", filter: "agNumberColumnFilter" },
    { field: "Rev Change +5%", filter: "agNumberColumnFilter" },
    { field: "Profit Change +5%", filter: "agNumberColumnFilter" },
    { field: "Rev Change -5%", filter: "agNumberColumnFilter" },
    { field: "Profit Change -5%", filter: "agNumberColumnFilter" },
    { field: "Val Chg 5% Decrease", filter: "agNumberColumnFilter" },
    { field: "Wkly Bskt Ct", filter: "agNumberColumnFilter" },
    { field: "Ela Price", filter: "agNumberColumnFilter" },
];

export const defaultColDef = {
    flex: 1,
    minWidth: 150,
    filter: "agTextColumnFilter",
    suppressHeaderMenuButton: true,
    suppressHeaderContextMenu: true,
};

export const rowData = [
    {
      UPC: "123456789012",
      "Product Desc": "Wireless Mouse",
      "Vendor Cost Zone Desc": "North America",
      "Vendor Id": "V1001",
      "# of Stores": 120,
      Department: "Electronics",
      Category: "Accessories",
      "Sub Category": "Mice",
      "Zone Name": "West Zone",
      Zone: "WZ-01",
      "Price Fam id": "PF123",
      "# of products": 200,
      "Export Rev": 50000,
      "Rec Profit Elast Chg": 5.2,
      "Markdown Amount": 10,
      "End Date": "2025-04-30",
      "Capture Rate": 85.4,
      "Exit Date": "2025-05-15",
      "Markdown Budget": 2000,
      "Markdown Variance": 150,
      "Item Add Date": "2024-12-01",
      "Competitor Impactful1": "Brand X",
      "Competitor Price Impactful1": 35.99,
      "Competitor Impactful2": "Brand Y",
      "Competitor Price Impactful2": 38.50,
      "Competitor Priority1": "Brand A",
      "Competitor Price Priority1": 34.99,
      "Competitor Priority2": "Brand B",
      "Competitor Price Priority2": 36.00,
      "Competitor Priority3": "Brand C",
      "Competitor Price Priority3": 37.50,
      "Rev Change +5%": 52500,
      "Profit Change +5%": 2500,
      "Rev Change -5%": 47500,
      "Profit Change -5%": -2500,
      "Val Chg 5% Decrease": -5,
      "Wkly Bskt Ct": 1200,
      "Ela Price": 1.2,
    },
    {
      UPC: "987654321098",
      "Product Desc": "Mechanical Keyboard",
      "Vendor Cost Zone Desc": "Europe",
      "Vendor Id": "V2002",
      "# of Stores": 85,
      Department: "Electronics",
      Category: "Accessories",
      "Sub Category": "Keyboards",
      "Zone Name": "Central Zone",
      Zone: "CZ-02",
      "Price Fam id": "PF456",
      "# of products": 150,
      "Export Rev": 75000,
      "Rec Profit Elast Chg": 4.8,
      "Markdown Amount": 12,
      "End Date": "2025-06-15",
      "Capture Rate": 78.9,
      "Exit Date": "2025-07-01",
      "Markdown Budget": 2500,
      "Markdown Variance": 200,
      "Item Add Date": "2025-01-15",
      "Competitor Impactful1": "Brand D",
      "Competitor Price Impactful1": 59.99,
      "Competitor Impactful2": "Brand E",
      "Competitor Price Impactful2": 62.50,
      "Competitor Priority1": "Brand F",
      "Competitor Price Priority1": 57.99,
      "Competitor Priority2": "Brand G",
      "Competitor Price Priority2": 60.00,
      "Competitor Priority3": "Brand H",
      "Competitor Price Priority3": 61.50,
      "Rev Change +5%": 78750,
      "Profit Change +5%": 3750,
      "Rev Change -5%": 71250,
      "Profit Change -5%": -3750,
      "Val Chg 5% Decrease": -5,
      "Wkly Bskt Ct": 900,
      "Ela Price": 1.4,
    },
];
  
  